blog/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.post_list, name='blog'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<post>[-\w]+)/$', views.post_detail, name='post_detail'),
]

personal_site/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from blog import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^froala_editor/', include('froala_editor.urls')),
    url(r'^blog/', include('blog.urls', namespace='blog', app_name='blog')),
]

blog/models.py
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.db import models
from django.utils import timezone
from froala_editor.fields import FroalaField


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, related_name='blog_posts')
    intro = models.TextField(max_length=250, default="")
    body = FroalaField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')
    objects = models.Manager()
    published = PublishedManager()

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.publish.year,
                                                 self.publish.strftime('%m'),
                                                 self.publish.strftime('%d'),
                                                 self.slug
                                                 ])

blog/views.py
from django.shortcuts import render,get_object_or_404
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from .models import Post
# Create your views here.
def index(request):
    return render (request,'index.html',{})
def post_list(request):
    object_list = Post.published.all()
    paginator = Paginator(object_list,5)
    page = request.GET.get('page', 1)
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    return render (request,'blog.html',{'page': page ,'posts':posts})


def post_detail (request,year,month,day,post):
    post = get_object_or_404(Post,slug=post,
                                  status ='published',
                                  publish__year = year,
                                  publish__month = month,
                                  publish__day = day) 
    return render(request,'post.html',{'post':post})

templates/blog.html
<!DOCTYPE html>
{% load staticfiles %}


<html class="no-js">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Mostafa Fotoh</title>



	<!-- Facebook and Twitter integration -->
	<meta property="og:title" content="" />
	<meta property="og:image" content="" />
	<meta property="og:url" content="" />
	<meta property="og:site_name" content="" />
	<meta property="og:description" content="" />
	<meta name="twitter:title" content="" />
	<meta name="twitter:image" content="" />
	<meta name="twitter:url" content="" />
	<meta name="twitter:card" content="" />


	<!-- Google Webfonts -->
	<link href='http://fonts.googleapis.com/css?family=Roboto:400,300,100,500' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Roboto+Slab:400,300,100,500' rel='stylesheet' type='text/css'>

	<!-- Animate.css -->
	<link rel="stylesheet" href="{% static 'css/animate.css' %}">
	<!-- Icomoon Icon Fonts-->
	<link rel="stylesheet" href="{% static 'css/icomoon.css' %}">
	<!-- Simple Line Icons -->
	<link rel="stylesheet" href="{% static 'css/simple-line-icons.css' %}">
	<!-- Theme Style -->
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
	<!-- Modernizr JS -->
	<script src="{% static 'js/modernizr-2.6.2.min.js' %}"></script>
	<!-- FOR IE9 below -->
	<!--[if lt IE 9]>
	<script src="{% static 'js/respond.min.js' %}"></script>
	<![endif]-->

</head>

<body>

	<header id="fh5co-header" role="banner">
		<nav class="navbar navbar-default" role="navigation">
			<div class="container">
				<div class="row">
					<div class="col-md-10 col-md-offset-1">
						<div class="navbar-header">
							<!-- Mobile Toggle Menu Button -->
							<a href="#" class="js-fh5co-nav-toggle fh5co-nav-toggle visible-xs-block" data-toggle="collapse" data-target="#fh5co-navbar"
							 aria-expanded="false" aria-controls="navbar"><i></i></a>
							<a class="navbar-brand" href="{% url 'index' %}">Mostafa Fotoh</a>
						</div>
						<div id="fh5co-navbar" class="navbar-collapse collapse">
							<ul class="nav navbar-nav navbar-right">
								<li><a href="{% url 'index' %}"><span>Home <span class="border"></span></span></a></li>
								<li class="active"><a href="{% url 'blog:blog' %}"><span>Blog<span class="border"></span></span></a></li>
								<li><a href="#"><span>Chart Builder<span class="border"></span></span></a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</nav>
	</header>
	<!-- END .header -->
	<div id="fh5co-main">
		<div class="fh5co-intro text-center">
			<div class="container">
				<div class="row">
					<div class="col-md-8 col-md-offset-2">
						<h1 class="intro-lead">Welcome to my blog</h1>
						<p class="">Check my connection bellow </p>
						<ul class="list-inline intro-social-buttons">
							<li>
								<a href="https://www.facebook.com/mostafa.foto7" class="btn btn-default btn-lg"><i class="fa fa-facebook fa-fw"></i> <span class="network-name">Facebook</span></a>
							</li>
							<li>
								<a href="https://twitter.com/FotohMostafa" class="btn btn-default btn-lg"><i class="fa fa-twitter fa-fw"></i> <span class="network-name">Twitter</span></a>
							</li>
							<li>
								<a href="https://github.com/mostafafotoh" class="btn btn-default btn-lg"><i class="fa fa-github fa-fw"></i> <span class="network-name">Github</span></a>
							</li>
							<li>
								<a href="https://www.linkedin.com/in/mostafa-fotoh/" class="btn btn-default btn-lg"><i class="fa fa-linkedin fa-fw"></i> <span class="network-name">Linkedin</span></a>
							</li>
						</ul>
					</div>
				</div>
			</div>
		</div>


		<!-- Main Content -->
		<div class="container">
			<div class="row">
				<div class="col-lg-8 col-md-10 mx-auto">
					{% for post in posts %}
					<div class="post-preview">
						<a href="{{ post.get_absolute_url }}">
							<h2 class="post-title">
								{{post.title}}
							</h2>
							<h3 class="post-subtitle">
								{{post.intro}}

							</h3>
						</a>
						<p class="post-meta">Posted by
							<a href="#">{{post.author}}</a> on {{post.publish}}</p>
					</div>
					<hr> {% endfor %}
					<!-- Pager -->
					<div class="clearfix">
						{% if posts.has_other_pages %}
						<ul class="pagination">
							{% if posts.has_previous %}
							<li><a href="?page={{ posts.previous_page_number }}">&laquo;</a></li>
							{% else %}
							<li class="disabled"><span>&laquo;</span></li>
							{% endif %} {% for i in posts.paginator.page_range %} {% if posts.number == i %}
							<li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span>
							</li>
							{% else %}
							<li><a href="?page={{ i }}">{{ i }}</a></li>
							{% endif %} {% endfor %} {% if users.has_next %}
							<li><a href="?page={{ posts.next_page_number }}">&raquo;</a></li>
							{% else %}
							<li class="disabled"><span>&raquo;</span></li>
							{% endif %} {% endif %}

					</div>
				</div>
			</div>
		</div>





	</div>

	<footer id="fh5co-footer">
		<div class="container">
			<div class="row">
				<div class="col-md-10 col-md-offset-1 text-center">
					<p>&copy; <a href="#">Mostafa Fotoh</a>. All Rights Reserved. </p>
				</div>
			</div>
		</div>
	</footer>


	<!-- jQuery -->
	<script src="{% static 'js/jquery.min.js' %}"></script>
	<!-- jQuery Easing -->
	<script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
	<!-- Bootstrap -->
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<!-- Waypoints -->
	<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
	<!-- Main JS -->
	<script src="{% static 'js/main.js' %}"></script>


</body>

</html>

templates/index.html
<!DOCTYPE html>
{% load staticfiles %}

<html class="no-js">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Mostafa Fotoh</title>



	<!-- Facebook and Twitter integration -->
	<meta property="og:title" content="" />
	<meta property="og:image" content="" />
	<meta property="og:url" content="" />
	<meta property="og:site_name" content="" />
	<meta property="og:description" content="" />
	<meta name="twitter:title" content="" />
	<meta name="twitter:image" content="" />
	<meta name="twitter:url" content="" />
	<meta name="twitter:card" content="" />

	<!-- Place favicon.ico and apple-touch-icon.png in the root directory -->

	<!-- Google Webfonts -->
	<link href='http://fonts.googleapis.com/css?family=Roboto:400,300,100,500' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Roboto+Slab:400,300,100,500' rel='stylesheet' type='text/css'>

	<!-- Animate.css -->
	<link rel="stylesheet" href="{% static 'css/animate.css' %}">
	<!-- Icomoon Icon Fonts-->
	<link rel="stylesheet" href="{% static 'css/icomoon.css' %}">
	<!-- Simple Line Icons -->
	<link rel="stylesheet" href="{% static 'css/simple-line-icons.css' %}">
	<!-- Theme Style -->
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
	<!-- Modernizr JS -->
	<script src="{% static 'js/modernizr-2.6.2.min.js' %}"></script>
	<!-- FOR IE9 below -->
	<!--[if lt IE 9]>
	<script src="{% static 'js/respond.min.js' %}"></script>
	<![endif]-->

</head>

<body>

	<header id="fh5co-header" role="banner">
		<nav class="navbar navbar-default" role="navigation">
			<div class="container">
				<div class="row">
					<div class="col-md-10 col-md-offset-1">
						<div class="navbar-header">
							<!-- Mobile Toggle Menu Button -->
							<a href="#" class="js-fh5co-nav-toggle fh5co-nav-toggle visible-xs-block" data-toggle="collapse" data-target="#fh5co-navbar"
							 aria-expanded="false" aria-controls="navbar"><i></i></a>
							<a class="navbar-brand" href="{% url 'index' %}">Mostafa Fotoh</a>
						</div>
						<div id="fh5co-navbar" class="navbar-collapse collapse">
							<ul class="nav navbar-nav navbar-right">
								<li class="active"><a href="{% url 'index' %}"><span>Home <span class="border"></span></span></a></li>
								<li><a href="{% url 'blog:blog' %}"><span>Blog<span class="border"></span></span></a></li>
								<li><a href="#"><span>Chart Builder<span class="border"></span></span></a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</nav>
	</header>
	<!-- END .header -->


	<div id="fh5co-main">
		<div class="fh5co-intro text-center">
			<div class="container">
				<div class="row">
					<div class="col-md-8 col-md-offset-2">
						<h1 class="intro-lead">Contact me if you need help</h1>
						<p class="">Check my Skills and chose any </p>
						<ul class="list-inline intro-social-buttons">
							<li>
								<a href="https://www.facebook.com/mostafa.foto7" class="btn btn-default btn-lg"><i class="fa fa-facebook fa-fw"></i> <span class="network-name">Facebook</span></a>
							</li>
							<li>
								<a href="https://twitter.com/FotohMostafa" class="btn btn-default btn-lg"><i class="fa fa-twitter fa-fw"></i> <span class="network-name">Twitter</span></a>
							</li>
							<li>
								<a href="https://github.com/mostafafotoh" class="btn btn-default btn-lg"><i class="fa fa-github fa-fw"></i> <span class="network-name">Github</span></a>
							</li>
							<li>
								<a href="https://www.linkedin.com/in/mostafa-fotoh/" class="btn btn-default btn-lg"><i class="fa fa-linkedin fa-fw"></i> <span class="network-name">Linkedin</span></a>
							</li>
						</ul>
					</div>
				</div>
			</div>
		</div>

		<div id="fh5co-portfolio">
			<div class="fh5co-portfolio-item ">
				<div class="fh5co-portfolio-figure animate-box" style="background-image: url(/static/images/intro-bg.png);"></div>
				<div class="fh5co-portfolio-description">
					<h2>Web Development</h2>
					<p>I am a Full stack Web Developer uses python Django Framework and Java EE " Servlets and JSP " as Backend , and "HTML5
						, CSS3 , javascript , jquery and Bootstrap " as Frontend , you can find apps developed by me on my <a target="_blank"
						 href="https://github.com/mostafafotoh">github</a>.</p>
				</div>
			</div>
			<div class="fh5co-portfolio-item fh5co-img-right">
				<div class="fh5co-portfolio-figure animate-box" style="background-image: url(/static/images/charts.jpeg);"></div>
				<div class="fh5co-portfolio-description">
					<h2>Data Visualization<br>and Analysis</h2>
					<p>I can analyze your data and display it in graphic form .. example of my previous projects <a target="_blank" href="https://github.com/mostafafotoh/InfoTimes-TwitterVIS">Twitter data Visualization</a>						for getting the Twitter Data and form them as a csv file , then you have a choice to visualize your csv data .</p>
				</div>
			</div>
			<div class="fh5co-portfolio-item ">
				<div class="fh5co-portfolio-figure animate-box" style="background-image: url(/static/images/blog.jpg);"></div>
				<div class="fh5co-portfolio-description">
					<h2>Computer Science <br>Blogger</h2>
					<p>I can write a Computer Science Blog in Both Language "English , Arabic " , you can read My Blogs Here in my website
						.</p>
				</div>
			</div>

		</div>





	</div>

	<footer id="fh5co-footer">
		<div class="container">
			<div class="row">
				<div class="col-md-10 col-md-offset-1 text-center">
					<p>&copy; <a href="#">Mostafa Fotoh</a>. All Rights Reserved. </p>
				</div>
			</div>
		</div>
	</footer>


	<!-- jQuery -->
	<script src="{% static 'js/jquery.min.js' %}"></script>
	<!-- jQuery Easing -->
	<script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
	<!-- Bootstrap -->
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<!-- Waypoints -->
	<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
	<!-- Main JS -->
	<script src="{% static 'js/main.js' %}"></script>


</body>

</html>

templates/post.html
<!DOCTYPE html>
{% load staticfiles %}
{% load addthis %}


<html class="no-js">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>{{post.title}}</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="Free HTML5 Template by FREEHTML5.CO" />
	<meta name="keywords" content="free html5, free template, free bootstrap, html5, css3, mobile first, responsive" />
	<meta name="author" content="FREEHTML5.CO" />

	<meta property="og:title" content="" />
	<meta property="og:image" content="" />
	<meta property="og:url" content="" />
	<meta property="og:site_name" content="" />
	<meta property="og:description" content="" />
	<meta name="twitter:title" content="" />
	<meta name="twitter:image" content="" />
	<meta name="twitter:url" content="" />
	<meta name="twitter:card" content="" />

	<!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
	<link rel="shortcut icon" href="favicon.ico">

	<!-- Google Webfonts -->
	<link href='http://fonts.googleapis.com/css?family=Roboto:400,300,100,500' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Roboto+Slab:400,300,100,500' rel='stylesheet' type='text/css'>

	<!-- Animate.css -->
	<link rel="stylesheet" href="{% static 'css/animate.css' %}">
	<!-- Icomoon Icon Fonts-->
	<link rel="stylesheet" href="{% static 'css/icomoon.css' %}">
	<!-- Simple Line Icons -->
	<link rel="stylesheet" href="{% static 'css/simple-line-icons.css' %}">
	<!-- Theme Style -->
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
	<!-- Modernizr JS -->
	<script src="{% static 'js/modernizr-2.6.2.min.js' %}"></script>
	<!-- FOR IE9 below -->
	<!--[if lt IE 9]>
	<script src="{% static 'js/respond.min.js' %}"></script>
	<![endif]-->
</head>

<body>
		

	<header id="fh5co-header" role="banner">
		<nav class="navbar navbar-default" role="navigation">
			<div class="container">
				<div class="row">
					<div class="col-md-10 col-md-offset-1">
						<div class="navbar-header">
							<!-- Mobile Toggle Menu Button -->
							<a href="#" class="js-fh5co-nav-toggle fh5co-nav-toggle visible-xs-block" data-toggle="collapse" data-target="#fh5co-navbar"
							 aria-expanded="false" aria-controls="navbar"><i></i></a>
							<a class="navbar-brand" href="{% url 'index' %}">Mostafa Fotoh</a>
						</div>
						<div id="fh5co-navbar" class="navbar-collapse collapse">
							<ul class="nav navbar-nav navbar-right">
								<li><a href="{% url 'index' %}"><span>Home <span class="border"></span></span></a></li>
								<li class="active"><a href="{% url 'blog:blog' %}"><span>Blog<span class="border"></span></span></a></li>
								<li><a href="#"><span>Chart Builder<span class="border"></span></span></a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</nav>
	</header>
	<!-- END .header -->



	<div id="fh5co-main">
		<div class="fh5co-intro text-center">
			<div class="container">
				<div class="row">
					<div class="col-md-8 col-md-offset-2">
						<h1 class="intro-lead">{{post.title}}</h1>

					</div>
				</div>
			</div>
		</div>

		<div id="fh5co-content">
			<div class="container">
				<div class="row">
					<div class="col-md-10 col-md-offset-1">
						<div class="row">
							<div class="col-md-3 animate-box">
								<h3>Paragraph</h3>
								<p>{{post.intro}}</p>
								<ul class="fh5co-list-check">
									<li>Posted by :<br> <a href="#">{{post.author}}</a></li>
									<li>Posted at :<br> <a href="#">{{post.publish}}</a></li>
									

								</ul>
							</div>
							<div class="col-md-9 animate-box">
								{{post.body|safe}}

							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		

		
	</div>

	<footer id="fh5co-footer">
		<div class="container">
			<div class="row">
				<div class="col-md-10 col-md-offset-1 text-center">
					<p>&copy; <a href="#">Mostafa Fotoh</a>. All Rights Reserved. </p>
				</div>
			</div>
		</div>
	</footer>

<!-- Go to www.addthis.com/dashboard to customize your tools -->

	<!-- jQuery -->
	<script src="{% static 'js/jquery.min.js' %}"></script>
	<!-- jQuery Easing -->
	<script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
	<!-- Bootstrap -->
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<!-- Waypoints -->
	<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
	<!-- Main JS -->
	<script src="{% static 'js/main.js' %}"></script>
	<!-- Go to www.addthis.com/dashboard to customize your tools --> 
	<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-599f8f78503e3551"></script> 
	<div class="addthis_sharing_toolbox"></div>
	{% addthis_widget %}

	
</body>

</html>